# Generated by Django 4.2.5 on 2023-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='chocolate',
            name='stores',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
